version: "3"
volumes:
  mongodb_data:

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    restart: always
    environment:
      - TELEGRAM_TOKEN=
      - OPENAI_API_KEY=
      - USE_CHATGPT_API=True
      - NEW_DIALOG_TIMEOUT=600
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
